
export class ConstPagesUtil {
  static readonly root: string = 'pages/RootPage'
  static readonly second: string = 'pages/SecondPage'
  static readonly third: string = 'pages/ThirdPage'
  static readonly measure: string = 'pages/MeasurePage'
  static readonly alterWindow: string = 'pages/WidowPage'
  static readonly appear: string = 'pages/AppearDemo'
}

export class ScreenUtil {
  static readonly FULL_SCREEN_WIDTH: string = '100%'
  static readonly FULL_SCREEN_HEIGHT: string = '100%'
}